### ISSUE TITLE
[BUG REPORT]: NULL values in WPC grid results

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#316] opened 2022-10-26 18:49 UTC
Report from Ashley in SAW

<img width="731" alt="image" src="https://user-images.githubusercontent.com/46494851/198110691-8d072e6b-5b62-4230-9bef-cc578504740a.png">

Direct link of download: https://cumulus-api.corps.cloud/cumulus/download/dss7/download_a3bbd4f2-128b-45fb-8157-9fa4ce2480b8.dss

![image](https://user-images.githubusercontent.com/46494851/198111135-fec69934-26cb-4efd-be25-2926ea5aa564.png)

**Comment by adamscarberry** [comment] 2022-11-01 18:47
Keep in mind both the grib and tif file above are CONUS (not clipped).  The clipping occurs during the DSS packaging process.

**Comment by adamscarberry** [comment] 2022-11-01 18:53
Here are the stats (abbreviated) for the clipped (Cape Fear River) tif for the same hour as above.

```
 gdalinfo p06m_2022110112f018.tif -stats

...

Metadata:
    GRIB_COMMENT=06 hr Total precipitation [kg/(m^2)]
    GRIB_DISCIPLINE=0(Meteorological)
    GRIB_ELEMENT=APCP06
    GRIB_FORECAST_SECONDS=43200
    GRIB_IDS=CENTER=7(US-NCEP) SUBCENTER=5(Hydrometeorological Prediction Center) MASTER_TABLE=2 LOCAL_TABLE=1 SIGNF_REF_TIME=1(Start_of_Forecast) REF_TIME=2022-11-01T12:00:00Z PROD_STATUS=0(Operational) TYPE=1(Forecast)
    GRIB_PDS_PDTN=8
    GRIB_PDS_TEMPLATE_ASSEMBLED_VALUES=1 8 2 0 180 255 255 1 12 1 0 0 1 0 -1 2022 11 2 6 0 0 1 0 1 255 1 6 1 0
    GRIB_PDS_TEMPLATE_NUMBERS=1 8 2 0 180 0 255 255 1 0 0 0 12 1 0 0 0 0 0 1 0 128 0 0 1 7 230 11 2 6 0 0 1 0 0 0 0 1 255 1 0 0 0 6 1 0 0 0 0
    GRIB_REF_TIME=1667304000
    GRIB_SHORT_NAME=0--1-SFC
    GRIB_UNIT=[kg/(m^2)]
    GRIB_VALID_TIME=1667368800
    STATISTICS_MAXIMUM=0
    STATISTICS_MEAN=0
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=0
    STATISTICS_VALID_PERCENT=100
```

**Comment by ktarbet** [comment] 2022-11-01 23:27
@katfeingold and I found where the Infinity is coming from in GridInfoFlat.java

```java
public boolean unflatten (int array[]) {
//....
 // deal with special cases of min, max, and mean values for all-null cases
    if (_minDataValue > _maxDataValue){
    	_maxDataValue = RMAConst.UNDEF_FLOAT;    
    	_minDataValue = RMAConst.UNDEF_FLOAT;
    	_meanDataValue = RMAConst.UNDEF_FLOAT;    	
    }
// where: public static final float UNDEF_FLOAT = Float.NEGATIVE_INFINITY;
```
the Infinity is intentional, but we could change this if other programs don't rely on that behavior?

**Comment by FHanbali** [comment] 2022-11-02 01:19
@adamscarberry can you share with me please the source grb files for the forecast timewindow 28July2022 throuhg 31July at least?

@ktarbet I believe the issue is not actually about the statistics reported in the Gridded DSS Record's header.  Rather it's about the array of values for grid cells, they seem to be coming out as -infiniti during conversion from original values of 0.

**Comment by jeffsuperglide** [comment] 2022-11-02 12:44
> @katfeingold and I found where the Infinity is coming from in GridInfoFlat.java
> 
> ```java
> public boolean unflatten (int array[]) {
> //....
>  // deal with special cases of min, max, and mean values for all-null cases
>     if (_minDataValue > _maxDataValue){
>     	_maxDataValue = RMAConst.UNDEF_FLOAT;    
>     	_minDataValue = RMAConst.UNDEF_FLOAT;
>     	_meanDataValue = RMAConst.UNDEF_FLOAT;    	
>     }
> // where: public static final float UNDEF_FLOAT = Float.NEGATIVE_INFINITY;
> ```
> 
> the Infinity is intentional, but we could change this if other programs don't rely on that behavior?

@ktarbet I thought we found this about a month ago?  I remember some DSS6 code that computes stats again before this evaluation.

GDAL is used in `tiffdss` to get the data array.  Stats are computed in `tiffdss` with concepts taken from DSS6/7 code.  @ktarbet is correct that it's about the grid data array and not stats computed from that array.  Evaluate the grib, GeoTiff, and the clipped GeoTiff only pulling out the data array.

**Comment by adamscarberry** [comment] 2022-11-02 13:50
This is a sample data set (based on my stats output above) that I can get you quickly:

[Archive.zip](https://github.com/USACE/cumulus/files/9920908/Archive.zip)

**Comment by ktarbet** [comment] 2022-11-02 15:43
@jeffsuperglide  Yes!   we recently had https://github.com/USACE/cumulus/issues/231 and  https://github.com/USACE/cumulus/issues/240 

More details on what we saw yesterday in the debugger:

All the data in the grid-data-array was listed as missing.
Then the statistics were re-computed during the DSS7->DSS6 conversion which creates the Infinity values for (min,max,mean), using the java code block above.

We need to change either:
* during the DSS7->DSS6 conversion
* MetVue/other software needs to handle the grid with all missing data. 

In a previous iteration, of this issue, we made a change to DssVue to handle this case better.

@FHanbali  Was there was a recent change to MetVue to handle this case?

**Comment by FHanbali** [comment] 2022-11-02 19:58
Thanks Adam.  Geotiff sample shows all zero (valid) values.  Either Geotiff conversion to DSS7 or DSS7 to DSS6 conversion is causing null values to be stored in final DSS product.

**Comment by jeffsuperglide** [comment] 2022-11-03 01:18
> This is a sample data set (based on my stats output above) that I can get you quickly:
> 
> [Archive.zip](https://github.com/USACE/cumulus/files/9920908/Archive.zip)

Two Tiff files are provided in the archive, conus_p06m_2022110112f018.tif and clipped_p06m_2022110112f018.tif.  `conus` has a no data value (nullValue) of 0 and the `clipped` no data value is -9999.  A no data value of 0 produces the following because all values == no data value.

```
Max Data Value: -2.0E38
Min Data Value: 2.0E38
Mean Data Value: NaN
```

Having -9999 (or != 0) results in zeros for stats.  The `packager` uses `gdal.Warp()` without defining the no data value; therefore, the no data value is taken from the source Tiff.  Packager writer dss7 could check for that no data value and set to some non-zero value.

**Comment by ktarbet** [comment] 2022-11-03 17:00
:: draft in progress table of workflow,   input welcome 


| Step| file | description  |  range of data |  no data value |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| 1| raw grib file| has 6 hour precip data mm | 0-30.5| not defined |
| 2| TIf - unclipped| 6 hour precipdata  |  0-24.9| not defined|
| 2| TIf - clipped| 6 hour precipdata  | 0-0|-9999 |
| 2| DSS v7| 6 hour precipdata  | n/a| -3.4028235E38|
| 2| DSS v6 | 6 hour precipdata  | n/a|-3.4028235E38 |

**Comment by adamscarberry** [comment] 2022-11-09 13:37
@jeffsuperglide and @brettpalmberg We ready for push to stable?

**Comment by jeffsuperglide** [comment] 2022-11-09 13:45
> @jeffsuperglide and @brettpalmberg We ready for push to stable?

I say yes.

**Comment by FHanbali** [comment] 2022-11-09 16:43
Let me know please if [cu](https://cumulus.corps.cloud/) is ready to have folks try out the fix.

**Comment by adamscarberry** [comment] 2022-11-09 19:41
@FHanbali @jeffsuperglide's patch has been applied to stable.  Ready for final verification.

**Comment by brettpalmberg** [comment] 2022-11-16 19:42
Kind ping 😃. This work is complete and awaiting final verification. Hoping we can officially close this issue.

@FHanbali @jeffsuperglide @adamscarberry @ktarbet

**Comment by brettpalmberg** [comment] 2022-11-22 02:45
Excellent! No worries and good teamwork all. Closing this issue now.

**Closed by brettpalmberg** 2022-11-22 02:45 UTC
Labels: bug
